name: Build and test Python
run-name: Building and testing MapPlotter on branch <${{ github.head_ref }}> to <${{ github.base_ref }}> by @${{ github.actor }}

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

defaults:
  run:
    shell: bash

jobs:    
  build_python:
    runs-on: ubuntu-20.04
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:${PWD}/Deps/lib
      C_INCLUDE_PATH:  $C_INCLUDE_PATH:${PWD}/Deps/include
    steps:
      - uses: actions/checkout@v3
      # Setup MPI and Python for this job
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.5
      # Run compilation and deployment
      - name: Set up dependencies
        run: make deps requirements
      - name: Install
        run: make install
        # Run Examples
      - name: Run examples
        run: |
          python Examples/example1.py
          python Examples/example2.py